dist: bionic
git:
  depth: 5 # use depth 5 to leave enough room for concurrent builds
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
language: ruby
stages:
- test
install:
- bundle config --local path .bundle/gems
- bundle --jobs 3 --retry 3
script: bundle exec ruby -w $(bundle exec which rake) spec
jobs:
  include:
  - stage: test
    rvm: 2.7.1
  - rvm: 2.3.8
